// ignore_for_file: unnecessary_string_escapes, equal_keys_in_map

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "Delivery Man Info": "Delivery Man Info",
          "Do you want to exit the app?": "Do you want to exit the app?", 
          "No": "No",
          "Yes": "Yes",
          "You need to log in first": "You need to log in first",
          "Profile": "Profile",
          "Pedidos": "Requests",
          "Pedidos   ": "Requests  ",
          "Search": "Search",
          "Home": "Home",
          "ERROR": "ERROR",
          "Confirm order": "Confirm order",
          "Adicionar morada": "Add adress",
          "Name of the address": "Nome do Endereço",
          "Rua do Outeiro": "Rua do Outeiro",
          "Address": "Morada",
          "Are you sure?": "Are you sure?",
          "Phone Number": "Phone Number",
          "City": "Cidade",
          "1º direito": "1º direito",
          "Enter to walk": "Enter to walk",
          "Postal Code": "Código Postal",
          "Enter Port Number": "Enter Port Number",
          "Country": "País",
          "Enter City": "Enter City",
          "State": "Estado",
          "Endereço padrão": "Default address",
          "Gravar": "Record",
          "Something went wrong": "Something went wrong",
          "Login successfully done": "Login successfully done",
          "Redefine password": "Redefine password",
          "Password": "Password",
          "Retype Password": "Retype Password",
          "Code": "Code",
          "Forgot your password": "Forgot your password",
          "Email": "Email",
          "Register": "Register",
          "Or login with": "Or login with",
          "Create Account": "Create Account",
          "First Name": "First Name",
          "First Name Can't be empty": "First Name Can't be empty",
          "Your Name": "Your Name",
          "Last Name": "Last Name",
          "Last Name Can't be empty": "Last Name Can't be empty",
          "Phone": "Phone",
          "phone number can't empty": "Phone number can't be empty",
          "Email Can't be empty": "Email Can't be empty",
          "Enter Password": "Enter Password",
          "Password must be  at least 6 characters": "Password must be  at least 6 characters",
          "Confim Password": "Confim Password",
          "Password Missmatch": "Password Missmatch",
          "Terms and Conditions": "Terms and Conditions",
          "I agree with terms and conditions and privacy policy":
              "I agree with terms and conditions and privacy policy",
          "Please accept the terms & condition!": "Please accept the terms & condition!",
          "Please check your internet connection": "Please check your internet connection",
          "Please login to perform this operation": "Please login to perform this operation",
          "Verify Otp": "Verify Otp",
          "verify provided otp": "verify provided otp",
          "Aplicar códido": "Aply code",
          "Aplicar": "Apply",
          "Enter Voucher": "Enter Voucher",
          "Voucher must be  at least 6 characters": "Voucher must be  at least 6 characters",
          "Adicionar código promocional": "Add promotional code",
          "Carrinho": "Cart",
          "O Teu Pedido": "Your request",
          " produto de ": "product",
          "Morada de entrega": "Delivery address",
          "Schedule delivery": "Schedule delivery",
          "Selecione um dia e hora": "Select a day and a hour",
          "Alterar": "Change",
          "Voucher Aplicado": "Aplyed voucher",
          "Tens um código promocional?": "You have a promotional code",
          "Sumário": "Summary",
          "Produtos": "Product",
          "Entrega": "Delivary",
          "Embalagem": "Package",
          "Total": "Total",
          "ar pedido": " request",
          "Select delivery Time": "Select delivery Time",
          "Agendar": "Schedule",
          "Cancelar": "Cancel",
          "Extras": "Extras",
          "Not Available": "Not Available",
          "Can't add more then 5 extra item": "Can't add more then 5 extra item",
          "Categories": "Categories",
          "Em destaque": "Highlighted",
          "Os seu favoritos": "Your favorits",
          "Opções": "Options",
          "Special Request": "Special Request",
          "Adicionar": "Add",
          "Add address To contiinue browsing": "Add address To contiinue browsing",
          "Entregar em": "Delivery in ",
          "Pesquisa": "Search",
          "Closed": "Closed",
          "VER TODOS": "SEE ALL",
          "Currently Not Available": "Currently Not Available",
          "Pedido": "Request",
          "Detalhes do pedido": "Request details",
          "Código de estafeta": "Code of the delivery boy",
          "Horário de entrega": "Delivery time",
          "Estado da encomenda": "Order state ",
          "Em curso": "On going",
          "Histórico": "History",
          "Pedir novamente": "Ask again",
          "Detalhes": "Details",
          "Seguir": "Follow",
          "Checkout": "Checkout",
          "Pagamenta": "Payment",
          "Add card": "Adicionar cartão",
          "Pagar": "Pay",
          "Select Payment Method": "Select Payment Method",
          "Perfil": "Profile",
          "As minhas moradas": "My adresses",
          "Ver os meus pedidos": "See my requests",
          "Contacto": "Contact",
          "Informações pessoais": "Personal information",
          "Preferências": "Preferences",
          "Idioma atual": "Current language",
          "Ajuda": "Help",
          "Enviar mensagem": "Send Message",
          "Conta": "Account",
          "You won't be able to revert this!": "You won't be able to revert this!",
          "Delete My Account": "Delete My Account",
          "You are about to Logout!": "You are about to Logout!",
          "Terminar sessão": "Log out",
          "Send Message": "Send Message",
          "Enter subject": "Enter subject",
          "Enter message": "Enter message",
          "message must be  at least 15 characters": "message must be  at least 15 characters",
          "No file selected": "No file selected",
          "Enter Value": "Enter Value",
          "Pesquisar": "Search",
          "Enter text": "Enter text",
          "Principais categorias": "Main categories",
          "Todas as categorias": "All categories",
          "Please select address from map": "Please select address from map",
          "Delivery Status": "Delivery Status",
          //new
          "Enter Address name": "Enter Address name",
          "Enter Address": "Enter Address",
          "Enter Postal Code": "Enter Postal Code",
          "Name on the card": "Name on the card",
          "Card Number": "Card Number",
          "Enter Card Name": "Enter Card Name",
          "Data de validade": "Expiration date",
          "Enter Expiry Date": "Enter Expiry Date",
          "Cartão padrão": "Standard card",
          "Cartão 1": "Card 1",
          "Old Password": "Old Password",
          "Enter oldPassword": "Enter oldPassword",
          "miss match old password": "miss match old password",
          "New Password": "New Password",
          "Enter newpassword": "Enter newpassword",
          "password must be 5 character": "password must be 5 character",
          " Password": " Password",
          "Enter password": "Enter password",
          "password not matched": "password not matched",
          "Andar": "To Walk",
          "Enter email": "Enter email",
          "email must be  at least 6 characters": "email must be  at least 6 characters",
          "NIF": "NIF",
          "Enter nif": "Enter nif",
          "nif must be  at least 6 characters": "nif must be  at least 6 characters",
          "Enter phone": "Enter phone",
          "phone must be  at least 6 characters": "phone must be  at least 6 characters",
          "Email": "Email",
          "Hoje": "Today",
          "Amanha": "Tomorrow",
          "Data connection is available.": "Data connection is available.",
          "You are not logged in": "You are not logged in",
          " minutes": " minutes",
          " unidades": " units",
          "Confirm Password": "Confirm Password",
          "Confirmed": "Confirmed",
          "Delivery Started": "Delivery Started",
          "Arrived at Shop": "Arrived at Shop",
          "Transit": "Transit",
          "Delivered": "Delivered",
          "On Transit": "On Transit",
          "ORDER FOR LATER": "ORDER FOR LATER",
          "OPEN NOW": "OPEN NOW",
          "This shop is closed now!": "This shop is closed now!",
          "Items": "Items",
          "Success": "Success",
          "Success with no content": "Success with no content",
          "Bad request. Try again later": "Bad request. Try again later",
          "User unauthorized. Try again later": "User unauthorized. Try again later",
          "Forbidden request. Try again later": "Forbidden request. Try again later",
          "Something went wrong. Try again later": "Something went wrong. Try again later",
          "URL not found. Try again later": "URL not found. Try again later",
          "Timeout. Try again later": "Timeout. Try again later",
          "Request canceled": "Request canceled",
          "Timeout. Try again later": "Timeout. Try again later",
          "Cache error. Try again later": "Cache error. Try again later",
          "Please check your internet connection": "Please check your internet connection",
          "Something went wrong": "Something went wrong",
        },

        //Portuguese LANGUAGE
        'pt_PT': {
          "Delivery Man Info": "Informações do entregador",
          "Do you want to exit the app?": "Queres sair da aplicação",
          "No": "Não",
          "Total": "Total",
          "Confirm order": "Confirmar pedido",
          "Yes": "Sim",
          "You need to log in first": "Percisas de entrar primeiro",
          "Profile": "Perfil",
          "Pedidos": "Pedidos",
          "Pedidos   ": "Pedidos   ",
          "No file selected": "Nenhum arquivo selecionado",
          "Are you sure?": "Tem certeza?",
          "Search": "Pesquisar",
          "Home": "Casa",
          "ERROR": "Erro",
          "Adicionar morada": "Adicionar morada",
          "Nome do Endereço": "Nome do Endereço",
          "Rua do Outeiro": "Rua do Outeiro",
          "Morada": "Morada",
          "Phone Number": "Telefone",
          "Cidade": "Cidade",
          "1º direito": "1º direito",
          "Enter to walk": "Entra para falar",
          "Código Postal": "Código Postal",
          "Enter Port Number": "Digita o numero da Porta",
          "País": "País",
          "Enter City": "Digita o nome da cidade",
          "Estado": "Estado",
          "Endereço padrão": "Endereço padrão",
          "Gravar": "Gravar",
          "Something went wrong": "Algo deu errado",
          "Login successfully done": "Entrou com sucesso",
          "Redefine password": "Muda a palavrapasse",
          "Password": "Palavrapasse",
          "Retype Password": "Reescreve a Palavrapasse",
          "Code": "Codigo",
          "Forgot your password": "Esquecestete da palavrapasse ",
          "Email": "Email",
          "Register": "Registrar",
          "Or login with": "Ou entra com",
          "Create Account": "Criar conta",
          "First Name": "Primeiro Nome",
          "First Name Can't be empty": "O primeiro nome não pode estar vazio",
          "Your Name": "O teu nome",
          "Last Name": "O teu ultimo nome",
          "Last Name Can't be empty": "O teu ultimo nome não pode estar vazio",
          "Phone": "Telemovel",
          "phone number can't empty": "O teu numero de telemovel não pode estar vazio",
          "Email Can't be empty": "o teu email não pode estar vazio",
          "Enter Password": "Digita a palavrapasse",
          "Password must be  at least 6 characters": " A palavrapasse tem de ter pelo menos 6 carcteres",
          "Confim Password": "a a palavrapasse",
          "Password Missmatch": "A palavrapasse não corresponde",
          "Terms and Conditions": "Termos e Condições",
          "I agree with terms and conditions and privacy policy":
              "Eu aceito os termos e condições da politica e privacidade",
          "Please accept the terms & condition!": "Por favor aceite os termos e condições!",
          "Please check your internet connection": "Por favor vê a tua conecção com a internet",
          "Please login to perform this operation": "Por favor entra para completar a ação",
          "Verify Otp": "Verificar Otp",
          "verify provided otp": "Verificação e dada pelo otp",
          "Aplicar códido": "Aplicar códido",
          "Aplicar": "Aplicar",
          "Enter Voucher": "Entredus o Voucher",
          "Voucher must be  at least 6 characters": "O voucher tem de ter pelo menos 6 caracteres",
          "Adicionar código promocional": "Adicionar código promocional",
          "Carrinho": "Carrinho",
          "O Teu Pedido": "O Teu Pedido",
          " produto de ": " produto de ",
          "Morada de entrega": "Morada de entrega",
          "Schedule delivery": "Agendar entrega",
          "Selecione um dia e hora": "Selecione um dia e hora",
          "Alterar": "Alterar",
          "Voucher Aplicado": "Voucher Aplicado",
          "Tens um código promocional?": "Tens um código promocional?",
          "Sumário": "Sumário",
          "Produtos": "Produtos",
          "Entrega": "Entrega",
          "Embalagem": "Embalagem",
          "Total": "Total",
          "ar pedido": "ar pedido",
          "Select delivery Time": "Seleciona um tempo de entrega",
          "Agendar": "Agendar",
          "Cancelar": "Cancelar",
          "Extras": "Extra",
          "Not Available": "Não está disponivel",
          "Can't add more then 5 extra item": "Não pode adicionar mais 5 itens extra",
          "Em destaque": "Em destaque",
          "Os seu favoritos": "Os seu favoritos",
          "Opções": "Opções",
          "Special Request": "Pedido especial",
          "Adicionar": "Adicionar",
          "Add address To contiinue browsing": "Adiciona a tua morada para continuares a navegar",
          "Entregar em": "Entregar em",
          "Pesquisa": "Pesquisa",
          "Closed": "Fechado",
          "VER TODOS": "VER TODOS",
          "Currently Not Available": "De momento não se encontra disponivel",
          "Pedido": "Pedido",
          "Detalhes do pedido": "Detalhes do pedido",
          "Código de estafeta": "Código de estafeta",
          "Horário de entrega": "Horário de entrega",
          "Estado da encomenda": "Estado da encomenda",
          "Em curso": "Em curso",
          "Histórico": "Histórico",
          "Pedir novamente": "Pedir novamente",
          "Detalhes": "Detalhes",
          "Seguir": "Seguir",
          "Checkout": "",
          "Pagamenta": "Pagamenta",
          "Adicionar cartão": "Adicionar cartão",
          "Pagar": "Pagar",
          "Select Payment Method": "Seleciona metodo de pagamento",
          "Perfil": "Perfil",
          "As minhas moradas": "As minhas moradas",
          "Ver os meus pedidos": "Ver os meus pedidos",
          "Contacto": "Contacto",
          "Informações pessoais": "Informações pessoais",
          "Preferências": "Preferências",
          "Idioma atual": "Idioma atual",
          "Ajuda": "Ajuda",
          "Enviar mensagem": "Enviar mensagem",
          "Conta": "Conta",
          "You won't be able to revert this!": "Não serás capaz de reverter estow!",
          "Delete My Account": "Apaga a minha conta",
          "You are about to Logout!": "Tu estás prestes a sair!",
          "Terminar sessão": "Terminar sessão",
          "Send Message": "Mandar menssagem",
          "Enter subject": "Digite assunto",
          "Enter message": "Digite menssagem",
          "message must be  at least 15 characters": "A menssagem tem de ter pelo menos 15 caracteres",
          "Nenhum arquivo selecionado": "Nenhum arquivo selecionado",
          "Enter Value": "Digite Valor",
          "Pesquisar": "Pesquisar",
          "Enter text": "Digite texto",
          "Principais categorias": "Categorias principais",
          "Todas as categorias": "Todas as categorias",
          "Categories": "Categorias",
          "Please select address from map": "Selecione o endereço no mapa",
          "Delivery Status": "Status de entrega",
          //new
          "Enter Address name": "Inserir nome do endereço",
          "Enter Address": "Inserir endereço",
          "Enter Postal Code": "Inserir código postal",
          "Name on the card": "Nome no cartão",
          "Card Number": "Número do cartão",
          "Enter Card Name": "Inserir nome do cartão",
          "Data de validade": "Data de validade",
          "Enter Expiry Date": "Inserir data de validade",
          "Cartão padrão": "Cartão padrão",
          "Cartão 1": "Cartão 1",
          "Old Password": "Senha antiga",
          "Enter oldPassword": "Inserir senha antiga",
          "miss match old password": "Senha antiga não corresponde",
          "New Password": "Nova senha",
          "Enter newpassword": "Inserir nova senha",
          "password must be 5 character": "A senha deve ter 5 caracteres",
          " Password": "ar senha",
          "Enter password": "Inserir ação de senha",
          "password not matched": "Senhas não correspondem",
          "Andar": "Andar",
          "Enter email": "Inserir email",
          "email must be at least 6 characters": "O email deve ter pelo menos 6 caracteres",
          "NIF": "NIF",
          "Enter nif": "Inserir NIF",
          "nif must be at least 6 characters": "O NIF deve ter pelo menos 6 caracteres",
          "Enter phone": "Inserir número de telefone",
          "phone must be at least 6 characters": "O número de telefone deve ter pelo menos 6 caracteres",
          "Email": "Email",
          "Hoje": "Hoje",
          "Amanha": "Amanhã",
          "Data connection is available.": "A conexão de dados está disponível",
          "You are not logged in": "Você não está conectado",
          " minutes": " minutos",
          " unidades": " unidades",
          "Confirm Password": "Confirme a senha",
          "Confirmed": "Confirmado",
          "Delivery Started": "Entrega Iniciada",
          "Arrived at Shop": "Chegou à Loja",
          "Transit": "Em Trânsito",
          "Delivered": "Entregue",
          "On Transit": "Em Trânsito",
          "ORDER FOR LATER": "ENCOMENDAR PARA DEPOIS",
          "OPEN NOW": "ABERTO AGORA",
          "This shop is closed now!": "Esta loja está fechada agora!", //pt
          "Items": "Itens", //pt
          "Success": "Sucesso",
          "Success with no content": "Sucesso sem conteúdo",
          "Bad request. Try again later": "Pedido inválido. Tente novamente mais tarde",
          "User unauthorized. Try again later": "Usuário não autorizado. Tente novamente mais tarde",
          "Forbidden request. Try again later": "Pedido proibido. Tente novamente mais tarde",
          "Something went wrong. Try again later": "Algo deu errado. Tente novamente mais tarde",
          "URL not found. Try again later": "URL não encontrada. Tente novamente mais tarde",
          "Timeout. Try again later": "Tempo limite excedido. Tente novamente mais tarde",
          "Request canceled": "Pedido cancelado",
          "Cache error. Try again later": "Erro de cache. Tente novamente mais tarde",
          "Please check your internet connection": "Por favor, verifique sua conexão com a internet",
          "Something went wrong": "Algo deu errado",
        },

        //Spanish Language
        'es_ES': {
          "Delivery Man Info": "Información del repartidor",
          "Do you want to exit the app?": "¿Quieres salir de la aplicación?",
          "No": "No",
          "Yes": "Sí",
          "Are you sure?": "Estas seguro?",
          "You need to log in first": "Necesitas iniciar sesión primero",
          "Profile": "Perfil",
          "Confirm order": "Confirmar pedido",
          "Pedidos": "Pedidos",
          "Pedidos   ": "Pedidos   ",
          "Search": "Buscar",
          "Home": "Inicio",
          "No file selected": "Ningún archivo seleccionado",
          "ERROR": "ERROR",
          "Adicionar morada": "Agregar dirección",
          "Nome do Endereço": "Nombre de la dirección",
          "Rua do Outeiro": "Calle do Outeiro",
          "Morada": "Dirección",
          "Phone Number": "Teléfono",
          "Cidade": "Ciudad",
          "1º direito": "1º derecho",
          "Enter to walk": "Presiona para caminar",
          "Código Postal": "Código Postal",
          "Enter Port Number": "Ingresa el número de puerto",
          "País": "País",
          "Enter City": "Ingresa la ciudad",
          "Estado": "Estado",
          "Endereço padrão": "Dirección predeterminada",
          "Gravar": "Guardar",
          "Something went wrong": "Algo salió mal",
          "Login successfully done": "Inicio de sesión exitoso",
          "Redefine password": "Restablecer contraseña",
          "Password": "Contraseña",
          "Retype Password": "Vuelve a escribir la contraseña",
          "Code": "Código",
          "Forgot your password": "¿Olvidaste tu contraseña?",
          "Email": "Correo electrónico",
          "Register": "Registrarse",
          "Or login with": "O inicia sesión con",
          "Create Account": "Crear cuenta",
          "First Name": "Nombre",
          "First Name Can't be empty": "El nombre no puede estar vacío",
          "Your Name": "Tu nombre",
          "Last Name": "Apellido",
          "Last Name Can't be empty": "El apellido no puede estar vacío",
          "Phone": "Teléfono",
          "phone number can't empty": "El número de teléfono no puede estar vacío",
          "Email Can't be empty": "El correo electrónico no puede estar vacío",
          "Enter Password": "Ingresa una contraseña",
          "Password must be at least 6 characters": "La contraseña debe tener al menos 6 caracteres",
          " Password": "ar contraseña",
          "Password Mismatch": "Las contraseñas no coinciden",
          "Terms and Conditions": "Términos y condiciones",
          "I agree with terms and conditions and privacy policy":
              "Acepto los términos y condiciones y la política de privacidad",
          "Please accept the terms & condition!": "¡Por favor, acepta los términos y condiciones!",
          "Please check your internet connection": "Por favor, verifica tu conexión a internet",
          "Please login to perform this operation": "Por favor, inicia sesión para realizar esta operación",
          "Verify Otp": "Verificar OTP",
          "Verify provided otp": "Verificar OTP proporcionado",
          "Aplicar código": "Aplicar código",
          "Aplicar": "Aplicar",
          "Enter Voucher": "Ingresa el cupón",
          "Voucher must be at least 6 characters": "El cupón debe tener al menos 6 caracteres",
          "Adicionar código promocional": "Agregar código promocional",
          "Carrinho": "Carrito",
          "O Teu Pedido": "Tu pedido",
          "produto de": "producto de",
          "Morada de entrega": "Dirección de entrega",
          "Schedule delivery": "Programar entrega",
          "Selecione um dia e hora": "Selecciona un día y hora",
          "Alterar": "Cambiar",
          "Voucher Aplicado": "Cupón aplicado",
          "Tens um código promocional?": "¿Tienes un código promocional?",
          "Sumário": "Resumen",
          "Produtos": "Productos",
          "Entrega": "Entrega",
          "Embalagem": "Embalaje",
          "Total": "Total",
          "ar pedido": "ar pedido",
          "Select delivery Time": "Seleccionar hora de entrega",
          "Agendar": "Programar",
          "Cancelar": "Cancelar",
          "Extras": "Extras",
          "Not Available": "No disponible",
          "Can't add more than 5 extra items": "No se pueden agregar más de 5 elementos extra",
          "Em destaque": "Destacados",
          "Os seu favoritos": "Tus favoritos",
          "Opções": "Opciones",
          "Special Request": "Solicitud especial",
          "Adicionar": "Agregar",
          "Add address To continue browsing": "Agregar dirección para seguir navegando",
          "Entregar em": "Entregar en",
          "Pesquisa": "Búsqueda",
          "Closed": "Cerrado",
          "VER TODOS": "VER TODOS",
          "Currently Not Available": "Actualmente no disponible",
          "Pedido": "Pedido",
          "Detalhes do pedido": "Detalles del pedido",
          "Código de estafeta": "Código de mensajero",
          "Horário de entrega": "Horario de entrega",
          "Estado da encomenda": "Estado del pedido",
          "Em curso": "En curso",
          "Histórico": "Historial",
          "Pedir novamente": "Pedir de nuevo",
          "Detalhes": "Detalles",
          "Seguir": "Seguir",
          "Checkout": "Pagar",
          "Pagamento": "Pago",
          "Adicionar cartão": "Agregar tarjeta",
          "Pagar": "Pagar",
          "Select Payment Method": "Seleccionar método de pago",
          "Perfil": "Perfil",
          "As minhas moradas": "Mis direcciones",
          "Ver os meus pedidos": "Ver mis pedidos",
          "Contacto": "Contacto",
          "Informações pessoais": "Información personal",
          "Preferências": "Preferencias",
          "Idioma atual": "Idioma actual",
          "Ajuda": "Ayuda",
          "Enviar mensagem": "Enviar mensaje",
          "Conta": "Cuenta",
          "You won't be able to revert this!": "¡No podrás revertir esto!",
          "Delete My Account": "Eliminar mi cuenta",
          "You are about to Logout!": "¡Estás a punto de cerrar sesión!",
          "Terminar sessão": "Cerrar sesión",
          "Send Message": "Enviar mensaje",
          "Enter subject": "Ingresa el asunto",
          "Enter message": "Ingresa el mensaje",
          "Message must be at least 15 characters": "El mensaje debe tener al menos 15 caracteres",
          "Nenhum arquivo selecionado": "Ningún archivo seleccionado",
          "Enter Value": "Ingresa el valor",
          "Pesquisar": "Buscar",
          "Enter text": "Ingresa texto",
          "Principais categorias": "Categorías principales",
          "Todas as categorias": "Todas las categorías",
          "Categories": "Categorías",
          "Please select address from map": "Por favor, selecciona una dirección del mapa",
          "Delivery Status": "Estado de entrega",
          "Enter Address name": "Ingresa el nombre de la dirección",
          "Enter Address": "Ingresa la dirección",
          "Enter Postal Code": "Ingresa el código postal",
          "Name on the card": "Nombre en la tarjeta",
          "Card Number": "Número de tarjeta",
          "Enter Card Name": "Ingresa el nombre de la tarjeta",
          "Data de validade": "Fecha de vencimiento",
          "Enter Expiry Date": "Ingresa la fecha de vencimiento",
          "Cartão padrão": "Tarjeta predeterminada",
          "Cartão 1": "Tarjeta 1",
          "Old Password": "Contraseña anterior",
          "Enter old Password": "Ingresa la contraseña anterior",
          "Miss match old password": "Contraseña anterior incorrecta",
          "New Password": "Nueva contraseña",
          "Enter new Password": "Ingresa la nueva contraseña",
          "Password must be 5 characters": "La contraseña debe tener 5 caracteres",
          " Password": "ar contraseña",
          "Enter  Password": "Ingresa la ación de contraseña",
          "Password not matched": "Las contraseñas no coinciden",
          "Andar": "Piso",
          "Enter email": "Ingresa el correo electrónico",
          "Email must be at least 6 characters": "El correo electrónico debe tener al menos 6 caracteres",
          "NIF": "NIF",
          "Enter NIF": "Ingresa el NIF",
          "NIF must be at least 6 characters": "El NIF debe tener al menos 6 caracteres",
          "Enter phone": "Ingresa el teléfono",
          "Phone must be at least 6 characters": "El teléfono debe tener al menos 6 caracteres",
          "Email": "Correo electrónico",
          "Hoje": "Hoy",
          "Amanha": "Mañana",
          "Data connection is available.": "La conexión de datos está disponible",
          "You are not logged in": "No has iniciado sesión",
          " minutes": " minutos",
          " unidades": " unidades",
          "Confirm Password": "Confirmar contraseña",
          "Confirmed": "Confirmado",
          "Delivery Started": "Entrega iniciada",
          "Arrived at Shop": "Llegó a la tienda",
          "Transit": "En tránsito",
          "Delivered": "Entregado",
          "On Transit": "En Tránsito",
          "ORDER FOR LATER": "PEDIR PARA DESPUÉS",
          "OPEN NOW": "ABIERTO AHORA",
          "This shop is closed now!": "¡Esta tienda está cerrada ahora!", //spanish
          "Items": "Artículos", //sp
          "Success": "Éxito",
          "Success with no content": "Éxito sin contenido",
          "Bad request. Try again later": "Solicitud incorrecta. Inténtalo de nuevo más tarde",
          "User unauthorized. Try again later": "Usuario no autorizado. Inténtalo de nuevo más tarde",
          "Forbidden request. Try again later": "Solicitud prohibida. Inténtalo de nuevo más tarde",
          "Something went wrong. Try again later": "Algo salió mal. Inténtalo de nuevo más tarde",
          "URL not found. Try again later": "URL no encontrada. Inténtalo de nuevo más tarde",
          "Timeout. Try again later": "Tiempo de espera agotado. Inténtalo de nuevo más tarde",
          "Request canceled": "Solicitud cancelada",
          "Cache error. Try again later": "Error de caché. Inténtalo de nuevo más tarde",
          "Please check your internet connection": "Por favor, verifica tu conexión a internet",
          "Something went wrong": "Algo salió mal",
        },

        //Russian Language
        'ru_RU': {
          "Delivery Man Info": "Информация о курьере",
          "Do you want to exit the app?": "Хотите выйти из приложения?",
          "No": "Нет",
          "Yes": "Да",
          "Are you sure?": "Вы уверены?",
          "You need to log in first": "Сначала вам нужно войти в систему",
          "Profile": "Профиль",
          "Confirm order": "Confirmar pedido",
          "No file selected": "Файл не выбран",
          "Pedidos": "Заказы",
          "Pedidos   ": "Заказы   ",
          "Search": "Поиск",
          "Home": "Главная",
          "ERROR": "Ошибка",
          "Adicionar morada": "Добавить адрес",
          "Nome do Endereço": "Имя адреса",
          "Rua do Outeiro": "Улица ду Оутейро",
          "Morada": "Адрес",
          "Phone Number": "Телефон",
          "Cidade": "Город",
          "1º direito": "1й этаж",
          "Enter to walk": "Вход",
          "Código Postal": "Почтовый индекс",
          "Enter Port Number": "Введите номер порта",
          "País": "Страна",
          "Enter City": "Введите город",
          "Estado": "Штат",
          "Endereço padrão": "Стандартный адрес",
          "Gravar": "Сохранить",
          "Something went wrong": "Чтото пошло не так",
          "Login successfully done": "Успешный вход в систему",
          "Redefine password": "Сбросить пароль",
          "Password": "Пароль",
          "Retype Password": "Повторите пароль",
          "Code": "Код",
          "Forgot your password": "Забыли пароль",
          "Email": "Электронная почта",
          "Register": "Регистрация",
          "Or login with": "Или войдите с помощью",
          "Create Account": "Создать аккаунт",
          "First Name": "Имя",
          "First Name Can't be empty": "Имя не может быть пустым",
          "Your Name": "Ваше имя",
          "Last Name": "Фамилия",
          "Last Name Can't be empty": "Фамилия не может быть пустой",
          "Phone": "Телефон",
          "phone number can't empty": "Номер телефона не может быть пустым",
          "Email Can't be empty": "Электронная почта не может быть пустой",
          "Enter Password": "Введите пароль",
          "Password must be at least 6 characters": "Пароль должен содержать не менее 6 символов",
          " Password": "Подтвердите пароль",
          "Password Mismatch": "Пароли не совпадают",
          "Terms and Conditions": "Условия и положения",
          "I agree with terms and conditions and privacy policy":
              "Я соглашаюсь с условиями и политикой конфиденциальности",
          "Please accept the terms & condition!": "Пожалуйста, примите условия и положения!",
          "Please check your internet connection": "Пожалуйста, проверьте подключение к интернету",
          "Please login to perform this operation": "Пожалуйста, войдите в систему, чтобы выполнить это действие",
          "Verify Otp": "Подтвердите OTP",
          "Verify provided otp": "Подтвердите предоставленный OTP",
          "Aplicar código": "Применить код",
          "Aplicar": "Применить",
          "Enter Voucher": "Введите купон",
          "Voucher must be at least 6 characters": "Купон должен содержать не менее 6 символов",
          "Adicionar código promocional": "Добавить промокод",
          "Carrinho": "Корзина",
          "O Teu Pedido": "Ваш заказ",
          " produto de ": " продукт из ",
          "Morada de entrega": "Адрес доставки",
          "Schedule delivery": "Запланировать доставку",
          "Selecione um dia e hora": "Выберите день и время",
          "Alterar": "Изменить",
          "Voucher Aplicado": "Примененный купон",
          "Tens um código promocional?": "У вас есть промокод?",
          "Sumário": "Итог",
          "Produtos": "Товары",
          "Entrega": "Доставка",
          "Embalagem": "Упаковка",
          "Total": "Итого",
          "ar pedido": "Подтвердить заказ",
          "Select delivery Time": "Выберите время доставки",
          "Agendar": "Запланировать",
          "Cancelar": "Отменить",
          "Extras": "Дополнительно",
          "Not Available": "Недоступно",
          "Can't add more than 5 extra items": "Нельзя добавить более 5 дополнительных позиций",
          "Em destaque": "В тренде",
          "Os seu favoritos": "Ваши избранные",
          "Opções": "Опции",
          "Special Request": "Особая просьба",
          "Adicionar": "Добавить",
          "Add address To continue browsing": "Добавьте адрес, чтобы продолжить просмотр",
          "Entregar em": "Доставить в",
          "Pesquisa": "Поиск",
          "Closed": "Закрыто",
          "VER TODOS": "ПОКАЗАТЬ ВСЕ",
          "Currently Not Available": "В настоящее время недоступно",
          "Pedido": "Заказ",
          "Detalhes do pedido": "Детали заказа",
          "Código de estafeta": "Код курьера",
          "Horário de entrega": "Время доставки",
          "Estado da encomenda": "Статус заказа",
          "Em curso": "В процессе",
          "Histórico": "История",
          "Pedir novamente": "Заказать еще раз",
          "Detalhes": "Детали",
          "Seguir": "Следить",
          "Checkout": "Оплата",
          "Pagamenta": "Оплата",
          "Adicionar cartão": "Добавить карту",
          "Pagar": "Оплатить",
          "Select Payment Method": "Выберите метод оплаты",
          "Perfil": "Профиль",
          "As minhas moradas": "Мои адреса",
          "Ver os meus pedidos": "Посмотреть мои заказы",
          "Contacto": "Контакт",
          "Informações pessoais": "Личная информация",
          "Preferências": "Предпочтения",
          "Idioma atual": "Текущий язык",
          "Ajuda": "Помощь",
          "Enviar mensagem": "Отправить сообщение",
          "Conta": "Аккаунт",
          "You won't be able to revert this!": "Вы не сможете вернуть это!",
          "Delete My Account": "Удалить мой аккаунт",
          "You are about to Logout!": "Вы собираетесь выйти из системы!",
          "Terminar sessão": "Выйти",
          "Send Message": "Отправить сообщение",
          "Enter subject": "Введите тему",
          "Enter message": "Введите сообщение",
          "Message must be at least 15 characters": "Сообщение должно содержать не менее 15 символов",
          "Nenhum arquivo selecionado": "Файл не выбран",
          "Enter Value": "Введите значение",
          "Pesquisar": "Поиск",
          "Enter text": "Введите текст",
          "Principais categorias": "Основные категории",
          "Todas as categorias": "Все категории",
          "Categories": "Категории",
          "Please select address from map": "Выберите адрес с карты",
          "Delivery Status": "Статус доставки",
          "Enter Address name": "Введите название адреса",
          "Enter Address": "Введите адрес",
          "Enter Postal Code": "Введите почтовый индекс",
          "Name on the card": "Имя на карте",
          "Card Number": "Номер карты",
          "Enter Card Name": "Введите имя карты",
          "Data de validade": "Срок действия",
          "Enter Expiry Date": "Введите срок действия",
          "Cartão padrão": "Стандартная карта",
          "Cartão 1": "Карта 1",
          "Old Password": "Старый пароль",
          "Enter old Password": "Введите старый пароль",
          "Miss match old password": "Неверный старый пароль",
          "New Password": "Новый пароль",
          "Enter new Password": "Введите новый пароль",
          "Password must be 5 characters": "Пароль должен состоять из 5 символов",
          " Password": "Подтвердите пароль",
          "Enter  Password": "Введите подтверждение пароля",
          "Password not matched": "Пароли не совпадают",
          "Andar": "Этаж",
          "Enter email": "Введите адрес электронной почты",
          "Email must be at least 6 characters": "Адрес электронной почты должен содержать не менее 6 символов",
          "NIF": "НИФ",
          "Enter NIF": "Введите НИФ",
          "NIF must be at least 6 characters": "НИФ должен содержать не менее 6 символов",
          "Enter phone": "Введите телефон",
          "Phone must be at least 6 characters": "Телефон должен содержать не менее 6 символов",
          "Email": "Адрес электронной почты",
          "Hoje": "Сегодня",
          "Amanha": "Завтра",
          "Data connection is available.": "Доступно подключение к сети данных.",
          "You are not logged in": "Вы не вошли в систему",
          " minutes": " минуты",
          " unidades": " единицы",
          "Confirm Password": "Подтвердите пароль",
          "Confirmed": "Подтверждено",
          "Delivery Started": "Доставка начата",
          "Arrived at Shop": "Прибыло в магазин",
          "Transit": "В пути",
          "Delivered": "Доставлено",
          "On Transit": "В пути",
          "ORDER FOR LATER": "ЗАКАЗАТЬ НА ПОТОМ",
          "OPEN NOW": "ОТКРЫТО СЕЙЧАС",
          "This shop is closed now!": "Этот магазин закрыт сейчас!", //russian
          "Items": "Товары", //ru
          "Success": "Успех",
          "Success with no content": "Успех без содержания",
          "Bad request. Try again later": "Неверный запрос. Попробуйте еще раз позже",
          "User unauthorized. Try again later": "Пользователь не авторизован. Попробуйте еще раз позже",
          "Forbidden request. Try again later": "Запрещенный запрос. Попробуйте еще раз позже",
          "Something went wrong. Try again later": "Что-то пошло не так. Попробуйте еще раз позже",
          "URL not found. Try again later": "URL не найден. Попробуйте еще раз позже",
          "Timeout. Try again later": "Время ожидания истекло. Попробуйте еще раз позже",
          "Request canceled": "Запрос отменен",
          "Timeout. Try again later": "Время ожидания истекло. Попробуйте еще раз позже",
          "Cache error. Try again later": "Ошибка кэша. Попробуйте еще раз позже",
          "Please check your internet connection": "Пожалуйста, проверьте ваше интернет-соединение",
          "Something went wrong": "Что-то пошло не так",
        },

        //Dutch Language
        'de_DE': {
          "Delivery Man Info": "Informatie Bezorger",
          "Do you want to exit the app?": "Wilt u de app afsluiten?",
          "No": "Nee",
          "No file selected": "Geen bestand geselecteerd",
          "Yes": "Ja",
          "Are you sure?": "Weet je het zeker?",
          "You need to log in first": "U moet eerst inloggen",
          "Profile": "Profiel",
          "Confirm order": "Confirmar pedido",
          "Pedidos": "Bestellingen",
          "Search": "Zoeken",
          "Home": "Startpagina",
          "ERROR": "FOUT",
          "Adicionar morada": "Adres toevoegen",
          "Nome do Endereço": "Naam van het adres",
          "Rua do Outeiro": "Straatnaam",
          "Morada": "Adres",
          "Phone Number": "Telefoonnummer",
          "Cidade": "Stad",
          "1º direito": "1e verdieping",
          "Enter to walk": "Druk op Enter om te lopen",
          "Código Postal": "Postcode",
          "Enter Port Number": "Voer poortnummer in",
          "País": "Land",
          "Enter City": "Voer stad in",
          "Estado": "Staat",
          "Endereço padrão": "Standaard adres",
          "Gravar": "Opslaan",
          "Something went wrong": "Er is iets misgegaan",
          "Login successfully done": "Inloggen succesvol voltooid",
          "Redefine password": "Wachtwoord opnieuw instellen",
          "Password": "Wachtwoord",
          "Retype Password": "Herhaal wachtwoord",
          "Code": "Code",
          "Forgot your password": "Wachtwoord vergeten",
          "Email": "Email",
          "Register": "Registreren",
          "Or login with": "Of inloggen met",
          "Create Account": "Account aanmaken",
          "First Name": "Voornaam",
          "First Name Can't be empty": "Voornaam mag niet leeg zijn",
          "Your Name": "Uw naam",
          "Last Name": "Achternaam",
          "Last Name Can't be empty": "Achternaam mag niet leeg zijn",
          "Phone": "Telefoon",
          "phone number can't empty": "Telefoonnummer mag niet leeg zijn",
          "Email Can't be empty": "Email mag niet leeg zijn",
          "Enter Password": "Voer wachtwoord in",
          "Password must be at least 6 characters": "Wachtwoord moet minimaal 6 tekens bevatten",
          "Confirm Password": "Bevestig wachtwoord",
          "Password Missmatch": "Wachtwoorden komen niet overeen",
          "Terms and Conditions": "Algemene voorwaarden",
          "I agree with terms and conditions and privacy policy":
              "Ik ga akkoord met de algemene voorwaarden en het privacybeleid",
          "Please accept the terms & condition!": "Accepteer de voorwaarden!",
          "Please check your internet connection": "Controleer uw internetverbinding",
          "Please login to perform this operation": "Log in om deze actie uit te voeren",
          "Verify Otp": "Otp verifiëren",
          "verify provided otp": "Verifieer de verstrekte otp",
          "Aplicar códido": "Code toepassen",
          "Aplicar": "Toepassen",
          "Enter Voucher": "Voer voucher in",
          "Voucher must be at least 6 characters": "Voucher moet minimaal 6 tekens bevatten",
          "Adicionar código promocional": "Promotiecode toevoegen",
          "Carrinho": "Winkelwagen",
          "O Teu Pedido": "Jouw bestelling",
          " produto de ": " product van ",
          "Morada de entrega": "Afleveradres",
          "Schedule delivery": "Levering plannen",
          "Selecione um dia e hora": "Selecteer een dag en tijd",
          "Alterar": "Wijzigen",
          "Voucher Aplicado": "Voucher toegepast",
          "Tens um código promocional?": "Heb je een promotiecode?",
          "Sumário": "Overzicht",
          "Produtos": "Producten",
          "Entrega": "Levering",
          "Embalagem": "Verpakking",
          "Total": "Totaal",
          "Confirmar pedido": "Bestelling bevestigen",
          "Select delivery Time": "Selecteer bezorgtijd",
          "Agendar": "Plannen",
          "Cancelar": "Annuleren",
          "Extras": "Extra's",
          "Not Available": "Niet beschikbaar",
          "Can't add more than 5 extra item": "Kan niet meer dan 5 extra items toevoegen",
          "Em destaque": "Uitgelicht",
          "Os seu favoritos": "Uw favorieten",
          "Opções": "Opties",
          "Special Request": "Speciaal verzoek",
          "Adicionar": "Toevoegen",
          "Add address To continue browsing": "Voeg een adres toe om door te gaan met browsen",
          "Entregar em": "Bezorgen op",
          "Pesquisa": "Zoeken",
          "Closed": "Gesloten",
          "VER TODOS": "BEKIJK ALLES",
          "Currently Not Available": "Momenteel niet beschikbaar",
          "Pedido": "Bestelling",
          "Detalhes do pedido": "Bestelgegevens",
          "Código de estafeta": "Koerierscode",
          "Horário de entrega": "Leveringstijd",
          "Estado da encomenda": "Bestelstatus",
          "Em curso": "Bezig",
          "Histórico": "Geschiedenis",
          "Pedir novamente": "Opnieuw bestellen",
          "Detalhes": "Details",
          "Seguir": "Volgen",
          "Checkout": "Afrekenen",
          "Pagamento": "Betaling",
          "Adicionar cartão": "Kaart toevoegen",
          "Pagar": "Betalen",
          "Select Payment Method": "Selecteer betaalmethode",
          "Perfil": "Profiel",
          "As minhas moradas": "Mijn adressen",
          "Ver os meus pedidos": "Mijn bestellingen bekijken",
          "Contacto": "Contact",
          "Informações pessoais": "Persoonlijke informatie",
          "Preferências": "Voorkeuren",
          "Idioma atual": "Huidige taal",
          "Ajuda": "Help",
          "Enviar mensagem": "Bericht verzenden",
          "Conta": "Account",
          "You won't be able to revert this!": "Dit kun je niet ongedaan maken!",
          "Delete My Account": "Mijn account verwijderen",
          "You are about to Logout!": "U staat op het punt uit te loggen!",
          "Terminar sessão": "Afmelden",
          "Send Message": "Bericht verzenden",
          "Enter subject": "Onderwerp invoeren",
          "Enter message": "Bericht invoeren",
          "message must be at least 15 characters": "Bericht moet minimaal 15 tekens bevatten",
          "Nenhum arquivo selecionado": "Geen bestand geselecteerd",
          "Enter Value": "Waarde invoeren",
          "Pesquisar": "Zoeken",
          "Enter text": "Tekst invoeren",
          "Principais categorias": "Hoofdcategorieën",
          "Todas as categorias": "Alle categorieën",
          "Categories": "Categorieën",
          "Please select address from map": "Selecteer een adres op de kaart",
          "Delivery Status": "Leveringsstatus",
          "Enter Address name": "Voer adresnaam in",
          "Enter Address": "Voer adres in",
          "Enter Postal Code": "Voer postcode in",
          "Name on the card": "Naam op de kaart",
          "Card Number": "Kaartnummer",
          "Enter Card Name": "Voer kaartnaam in",
          "Data de validade": "Vervaldatum",
          "Enter Expiry Date": "Voer vervaldatum in",
          "Cartão padrão": "Standaard kaart",
          "Cartão 1": "Kaart 1",
          "Old Password": "Oud wachtwoord",
          "Enter old Password": "Voer oud wachtwoord in",
          "Miss match old password": "Oud wachtwoord komt niet overeen",
          "New Password": "Nieuw wachtwoord",
          "Enter new Password": "Voer nieuw wachtwoord in",
          "Password must be 5 characters": "Wachtwoord moet 5 tekens bevatten",
          "Enter confirm Password": "Bevestig wachtwoord",
          "Password not matched": "Wachtwoorden komen niet overeen",
          "Andar": "Verdieping",
          "Enter email": "Voer emailadres in",
          "Email must be at least 6 characters": "Emailadres moet minimaal 6 tekens bevatten",
          "NIF": "BTWnummer",
          "Enter NIF": "Voer BTWnummer in",
          "NIF must be at least 6 characters": "BTWnummer moet minimaal 6 tekens bevatten",
          "Enter phone": "Voer telefoonnummer in",
          "Phone must be at least 6 characters": "Telefoonnummer moet minimaal 6 tekens bevatten",
          "Hoje": "Vandaag",
          "Amanha": "Morgen",
          "Data connection is available.": "Dataconnectie is beschikbaar",
          "You are not logged in": "U bent niet ingelogd",
          " minutes": " minuten",
          " unidades": " eenheden",
          "Confirmed": "Bevestigd",
          "Delivery Started": "Levering gestart",
          "Arrived at Shop": "Aangekomen bij de winkel",
          "Transit": "Onderweg",
          "Delivered": "Geleverd",
          "On Transit": "Onderweg",
          "ORDER FOR LATER": "BESTELLEN VOOR LATER",
          "OPEN NOW": "NU OPEN",
          "This shop is closed now!": "Deze winkel is nu gesloten!", //dutch
          "Items": "Items", //du
          "Success": "Succes",
          "Success with no content": "Succes zonder inhoud",
          "Bad request. Try again later": "Foutief verzoek. Probeer het later opnieuw",
          "User unauthorized. Try again later": "Gebruiker niet geautoriseerd. Probeer het later opnieuw",
          "Forbidden request. Try again later": "Verzoek verboden. Probeer het later opnieuw",
          "Something went wrong. Try again later": "Er is iets misgegaan. Probeer het later opnieuw",
          "URL not found. Try again later": "URL niet gevonden. Probeer het later opnieuw",
          "Timeout. Try again later": "Time-out. Probeer het later opnieuw",
          "Request canceled": "Verzoek geannuleerd",
          "Cache error. Try again later": "Cachefout. Probeer het later opnieuw",
          "Please check your internet connection": "Controleer uw internetverbinding alstublieft",
          "Something went wrong": "Er is iets misgegaan",
        },

        //French Language
        'fr_FR': {
          "Delivery Man Info": "Informations sur le livreur",
          "Do you want to exit the app?": "Voulezvous quitter l'application?",
          "No": "Non",
          "Yes": "Oui",
          "No file selected": "Aucun fichier sélectionné",
          "Are you sure?": "Es-tu sûr?",
          "You need to log in first": "Vous devez d'abord vous connecter",
          "Profile": "Profil",
          "Pedidos": "Commandes",
          "Pedidos   ": "Commandes ",
          "Search": "Rechercher",
          "Home": "Accueil",
          "ERROR": "ERREUR",
          "Adicionar morada": "Ajouter une adresse",
          "Nome do Endereço": "Nom de l'adresse",
          "Rua do Outeiro": "Rue du Outeiro",
          "Morada": "Adresse",
          "Phone Number": "Téléphone",
          "Cidade": "Ville",
          "1º direito": "1er droit",
          "Enter to walk": "Appuyez pour marcher",
          "Código Postal": "Code postal",
          "Enter Port Number": "Entrer le numéro de port",
          "País": "Pays",
          "Enter City": "Entrer la ville",
          "Estado": "État",
          "Endereço padrão": "Adresse par défaut",
          "Gravar": "Enregistrer",
          "Something went wrong": "Quelque chose s'est mal passé",
          "Login successfully done": "Connexion réussie",
          "Redefine password": "Réinitialiser le mot de passe",
          "Password": "Mot de passe",
          "Retype Password": "Retapez le mot de passe",
          "Code": "Code",
          "Forgot your password": "Mot de passe oublié",
          "Email": "Email",
          "Register": "S'inscrire",
          "Or login with": "Ou connectezvous avec",
          "Create Account": "Créer un compte",
          "First Name": "Prénom",
          "First Name Can't be empty": "Le prénom ne peut pas être vide",
          "Your Name": "Votre nom",
          "Last Name": "Nom de famille",
          "Last Name Can't be empty": "Le nom de famille ne peut pas être vide",
          "Phone": "Téléphone",
          "phone number can't empty": "Le numéro de téléphone ne peut pas être vide",
          "Email Can't be empty": "L'email ne peut pas être vide",
          "Enter Password": "Entrer le mot de passe",
          "Password must be at least 6 characters": "Le mot de passe doit contenir au moins 6 caractères",
          "Confirm Password": "Confirmer le mot de passe",
          "Password Missmatch": "Les mots de passe ne correspondent pas",
          "Terms and Conditions": "Termes et conditions",
          "I agree with terms and conditions and privacy policy":
              "J'accepte les termes et conditions et la politique de confidentialité",
          "Please accept the terms & condition!": "Veuillez accepter les termes et conditions!",
          "Please check your internet connection": "Veuillez vérifier votre connexion Internet",
          "Please login to perform this operation": "Veuillez vous connecter pour effectuer cette opération",
          "Verify Otp": "Vérifier OTP",
          "verify provided otp": "Vérifier l'OTP fourni",
          "Aplicar códido": "Appliquer le code",
          "Aplicar": "Appliquer",
          "Enter Voucher": "Entrer le bon",
          "Voucher must be at least 6 characters": "Le bon doit contenir au moins 6 caractères",
          "Adicionar código promocional": "Ajouter un code promotionnel",
          "Carrinho": "Panier",
          "O Teu Pedido": "Votre commande",
          " produto de ": " produit de ",
          "Morada de entrega": "Adresse de livraison",
          "Schedule delivery": "Planifier la livraison",
          "Selecione um dia e hora": "Sélectionnez un jour et une heure",
          "Alterar": "Modifier",
          "Voucher Aplicado": "Bon appliqué",
          "Tens um código promocional?": "Vous avez un code promotionnel?",
          "Sumário": "Sommaire",
          "Produtos": "Produits",
          "Entrega": "Livraison",
          "Embalagem": "Emballage",
          "Total": "Total",
          "Confirmar pedido": "Confirmer la commande",
          "Select delivery Time": "Sélectionnez l'heure de livraison",
          "Agendar": "Planifier",
          "Cancelar": "Annuler",
          "Extras": "Suppléments",
          "Not Available": "Non disponible",
          "Can't add more than 5 extra items": "Impossible d'ajouter plus de 5 articles supplémentaires",
          "Em destaque": "En vedette",
          "Os seu favoritos": "Vos favoris",
          "Opções": "Options",
          "Special Request": "Demande spéciale",
          "Adicionar": "Ajouter",
          "Add address To continue browsing": "Ajoutez une adresse pour continuer à naviguer",
          "Entregar em": "Livrer à",
          "Pesquisa": "Recherche",
          "Closed": "Fermé",
          "VER TODOS": "VOIR TOUS",
          "Currently Not Available": "Actuellement non disponible",
          "Pedido": "Commande",
          "Detalhes do pedido": "Détails de la commande",
          "Código de estafeta": "Code du livreur",
          "Horário de entrega": "Horaire de livraison",
          "Estado da encomenda": "État de la commande",
          "Em curso": "En cours",
          "Histórico": "Historique",
          "Pedir novamente": "Commander à nouveau",
          "Detalhes": "Détails",
          "Seguir": "Suivre",
          "Checkout": "Paiement",
          "Pagamenta": "Paiement",
          "Adicionar cartão": "Ajouter une carte",
          "Pagar": "Payer",
          "Select Payment Method": "Sélectionner le mode de paiement",
          "Perfil": "Profil",
          "As minhas moradas": "Mes adresses",
          "Ver os meus pedidos": "Voir mes commandes",
          "Contacto": "Contact",
          "Informações pessoais": "Informations personnelles",
          "Preferências": "Préférences",
          "Idioma atual": "Langue actuelle",
          "Ajuda": "Aide",
          "Enviar mensagem": "Envoyer un message",
          "Conta": "Compte",
          "You won't be able to revert this!": "Vous ne pourrez pas revenir en arrière !",
          "Delete My Account": "Supprimer mon compte",
          "You are about to Logout!": "Vous êtes sur le point de vous déconnecter !",
          "Terminar sessão": "Se déconnecter",
          "Send Message": "Envoyer un message",
          "Enter subject": "Saisissez le sujet",
          "Enter message": "Saisissez le message",
          "message must be at least 15 characters": "le message doit contenir au moins 15 caractères",
          "Nenhum arquivo selecionado": "Aucun fichier sélectionné",
          "Enter Value": "Saisissez la valeur",
          "Pesquisar": "Rechercher",
          "Enter text": "Saisissez du texte",
          "Principais categorias": "Catégories principales",
          "Todas as categorias": "Toutes les catégories",
          "Categories": "Catégories",
          "Please select address from map": "Veuillez sélectionner une adresse sur la carte",
          "Delivery Status": "Statut de la livraison",
          "Enter Address name": "Saisissez le nom de l'adresse",
          "Enter Address": "Saisissez l'adresse",
          "Enter Postal Code": "Saisissez le code postal",
          "Name on the card": "Nom sur la carte",
          "Card Number": "Numéro de carte",
          "Enter Card Name": "Saisissez le nom de la carte",
          "Data de validade": "Date d'expiration",
          "Enter Expiry Date": "Saisissez la date d'expiration",
          "Cartão padrão": "Carte par défaut",
          "Cartão 1": "Carte 1",
          "Old Password": "Ancien mot de passe",
          "Enter old Password": "Saisissez l'ancien mot de passe",
          "Miss match old password": "Ancien mot de passe incorrect",
          "New Password": "Nouveau mot de passe",
          "Enter new Password": "Saisissez le nouveau mot de passe",
          "Password must be 5 characters": "Le mot de passe doit contenir 5 caractères",
          "Confirm Password": "Confirmez le mot de passe",
          "Enter confirm Password": "Confirmez le mot de passe",
          "Password not matched": "Les mots de passe ne correspondent pas",
          "Andar": "Étage",
          "Enter email": "Saisissez l'adresse email",
          "Email must be at least 6 characters": "L'adresse email doit contenir au moins 6 caractères",
          "NIF": "NIF",
          "Enter NIF": "Saisissez le NIF",
          "NIF must be at least 6 characters": "Le NIF doit contenir au moins 6 caractères",
          "Enter phone": "Saisissez le numéro de téléphone",
          "Phone must be at least 6 characters": "Le numéro de téléphone doit contenir au moins 6 caractères",
          "Email": "Email",
          "Hoje": "Aujourd'hui",
          "Amanha": "Demain",
          "Data connection is available.": "La connexion de données est disponible.",
          "You are not logged in": "Vous n'êtes pas connecté",
          " minutes": " minutes",
          " unidades": " unités",
          "Confirmed": "Confirmé",
          "Delivery Started": "Livraison commencée",
          "Arrived at Shop": "Arrivé au magasin",
          "Transit": "En transit",
          "Delivered": "Livré",
          "On Transit": "En Transit",
          "ORDER FOR LATER": "COMMANDER POUR PLUS TARD",
          "OPEN NOW": "OUVERT MAINTENANT",
          "This shop is closed now!": "Ce magasin est fermé maintenant!",
          "Items": "Articles", //fr
          "Success": "Succès",
          "Success with no content": "Succès sans contenu",
          "Bad request. Try again later": "Requête incorrecte. Réessayez plus tard",
          "User unauthorized. Try again later": "Utilisateur non autorisé. Réessayez plus tard",
          "Forbidden request. Try again later": "Requête interdite. Réessayez plus tard",
          "Something went wrong. Try again later": "Quelque chose s'est mal passé. Réessayez plus tard",
          "URL not found. Try again later": "URL non trouvée. Réessayez plus tard",
          "Timeout. Try again later": "Délai dépassé. Réessayez plus tard",
          "Request canceled": "Requête annulée",
          "Cache error. Try again later": "Erreur de cache. Réessayez plus tard",
          "Please check your internet connection": "Veuillez vérifier votre connexion Internet",
          "Something went wrong": "Quelque chose s'est mal passé",
        }
      };
}
